project:
  type: book

book:
  title: "Manual de Laboratorio de Biología de las Plantas"
  author: 
    - Autor 1
    - Autor 2
  date: "2023-02-03"
  date-format: iso
  #cover-image: images/cover.png
  page-navigation: true
  search: true
  downloads: pdf
  sidebar: 
    logo: images/cover.png


  chapters:
    - index.qmd
    - part: "Laboratorios"
      chapters:
        - laboratorio-01.qmd
        - laboratorio-02.qmd
        - laboratorio-03.qmd
        - laboratorio-04.qmd
        - laboratorio-05.qmd
        - laboratorio-06.qmd
        - laboratorio-07.qmd
        - laboratorio-08.qmd
        - laboratorio-09.qmd
        - laboratorio-10.qmd
        - laboratorio-11.qmd
    - recursos.qmd
    - referencias.qmd

bibliography: references.bib

lang: es

format:
  html:
    theme: cosmo
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt



