project:
  type: book

book:
  title: "Biología de las Plantas: Manual de Laboratorio"
  author: 
    - name: Fernando Alveiro Alzate Guarin
      orcid: 0000-0002-4916-8897
      email: alveiro.alzate@udea.edu.co
#      affiliations: Grupo de Estudios Botánicos GEOBOTA, Instituto de Biología, Facultad de Ciencias Exactas y Naturales, Universidad de Antioquia UdeA, Calle 70 No. 52-21, Medellín, Colombia
    - name: Felipe Alfonso Cardona Naranjo
#      affiliations: Herbario Universidad de Antioquia HUA, Instituto de Biología, Facultad de Ciencias Exactas y Naturales, Universidad de Antioquia UdeA, Calle 70 No. 52-21, Medellín, Colombia
    - name: Álex Espinosa Correa
      orcid: 0000-0002-7353-1182
#      affiliations: Grupo de Estudios Botánicos GEOBOTA, Instituto de Biología, Facultad de Ciencias Exactas y Naturales, Universidad de Antioquia UdeA, Calle 70 No. 52-21, Medellín, Colombia
    
  date: last-modified
  date-format: iso
  
  cover-image: images/cover.png
  page-navigation: true
  search: true
  reader-mode: true
  
  site-url: https://alexespinosaco.github.io/manual-laboratorio-biologia-plantas/
  repo-url: https://github.com/alexespinosaco/manual-laboratorio-biologia-plantas
  downloads: [pdf, epub]
  #sidebar: 
    #logo: images/cover.png
  google-analytics: "G-ZMDTRMYQMG"

  chapters:
    - index.qmd
    - part: "Laboratorios"
      chapters:
        - recorrido.qmd
        - citologia.qmd
        - histologia-I.qmd
        - histologia-II.qmd
        - diversidad-I.qmd
        - diversidad-II.qmd
        - raiz.qmd
        - tallo.qmd
        - hoja.qmd
        - flor.qmd
        - fruto.qmd
    - recursos.qmd
    - referencias.qmd

bibliography: references.bib
csl: apa.csl

comments: 
  hypothesis:
    theme: clean

lang: es

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    link-external-icon: false
    link-external-newwindow: true


nocite: |
  @bowes2013, @dávilavillamizar2003, @dickison2000, @evert2006, @evert2013, @fontquer2001, 
  @graham2013, @jones2012, @mauseth2016, @nabors2006, @paniagua2007, @pendarvis2018, 
  @pérez-garcía2002, @schweingruber2006, @schweingruber2011, @schweingruber2013, @simpson2019, @singh2019 


