project:
  type: book

book:
  title: "Manual de Laboratorio de Biología de las Plantas"
  author: "Fernando Alzate"
  author: "Felipe Cardona"
  date: "2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

lang: es
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



